theme: minima
title: Decision theory, some thoughts
author: maurerfl
email: 
description: > # this means to ignore newlines until "baseurl:"
  I'm currently learning decision theory and game theory in my university class "decision support".
  Here I want to share some thoughts about it

# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  maurerfl # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
